# Generated by Django 2.2.5 on 2019-10-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Порядковый номер')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('width', models.FloatField(verbose_name='Ширина')),
            ],
        ),
        migrations.CreateModel(
            name='FilePath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FilePathField(verbose_name='Путь к csv')),
            ],
        ),
    ]
