# Generated by Django 2.2.5 on 2019-11-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='width',
            field=models.IntegerField(verbose_name='Ширина'),
        ),
    ]
